# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 00:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    replaces = [(b'maps', '0001_initial'), (b'maps', '0002_auto_20160114_2034'), (b'maps', '0003_auto_20160115_0106'), (b'maps', '0004_auto_20160123_1826')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_id', models.TextField(max_length=32)),
                ('view_id', models.TextField(max_length=32)),
                ('name', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MapFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.SmallIntegerField(choices=[(1, 'Reveal')])),
                ('data', jsonfield.fields.JSONField(default=dict)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='maps.Map')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='map',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='map',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
