# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-24 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_squashed_0004_auto_20160123_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='mapname',
            field=models.TextField(default='independence', max_length=100),
            preserve_default=False,
        ),
    ]
