# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-15 01:06
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_auto_20160114_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mapfeature',
            name='data',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
