# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-23 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20160115_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='map',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
